@BookApi_HostAddress = http://localhost:5117

GET {{BookApi_HostAddress}}/books
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNhaW8iLCJzdWIiOiJDYWlvIiwianRpIjoiZGFhMzcwZmQiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDozODAzNCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzE0IiwiaHR0cDovL2xvY2FsaG9zdDo1MTE3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEyMCJdLCJuYmYiOjE3MjE5NDIwNjEsImV4cCI6MTcyOTg5MDg2MSwiaWF0IjoxNzIxOTQyMDYyLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.0hRJ7CR6qFYRk_-xUaeU-YVCd7lZqXUTDnKayMGMNOU

###
GET {{BookApi_HostAddress}}/books/3
###
POST {{BookApi_HostAddress}}/books
Content-Type: application/json

{
    "name": "Foundation",
    "author": "-",
    "categoryId": 4,
    "price": 59.99,
    "releaseDate": "1994-07-05"
  }
 
###
PUT {{BookApi_HostAddress}}/books/2
Content-Type: application/json

  {
    "name": "Hobbit",
    "author": "Tolken",
    "categoryId": 3,
    "price": 19.99,
    "releaseDate": "1994-07-05"
  }

###
DELETE {{BookApi_HostAddress}}/books/2

###
GET {{BookApi_HostAddress}}/books/mybooks
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiNDNlN2NkOWUiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjM4MDM0IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTQiLCJodHRwOi8vbG9jYWxob3N0OjUxMTciLCJodHRwczovL2xvY2FsaG9zdDo3MTIwIl0sIm5iZiI6MTcyMTk2OTkwNSwiZXhwIjoxNzI5OTE4NzA1LCJpYXQiOjE3MjE5Njk5MDYsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.7cjuUNE-DQHhudcFdj8yFIxM6_4EV1bLJ5Wxv6WL-y8